version: '2.2'

services:
  web:
    depends_on:
      - db
    image: wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      # - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: digitalocean
      WORDPRESS_DB_USER: digitalocean
      WORDPRESS_DB_NAME: digitalocean
    mem_limit: 650m
    cpus: .8
  db:
    image: mysql:5.5
    expose:
      - 3306
    volumes:
      - ./.data/db:/var/lib/mysql
    restart: always
    mem_limit: 300m
    cpus: .15
    environment:
      MYSQL_ROOT_PASSWORD: digitalocean
      MYSQL_DATABASE: digitalocean
      MYSQL_USER: digitalocean
      MYSQL_PASSWORD: digitalocean
